export const LOGIN_PAGE = "/login"
export const REGISTER_PAGE = "/register"
export const POKEDEX_PAGE = "Pokedex"
export const HOME_PAGE = "Home"
export const PROFILE_PAGE = "Profile"
export const BOTTOM_NAV_BAR = "/bottomNavBar"
export const CREATE_PAGE = "/create"
export const EDIT_PAGE = "/edit"